# Generated by Django 4.2.9 on 2024-07-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0003_alter_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(
                choices=[("module", "Модуль"), ("course", "Курс")],
                max_length=10,
                verbose_name="Тип подписки",
            ),
        ),
    ]
