# Generated by Django 4.2.9 on 2024-07-04 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0005_alter_subscription_subscription_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module",
                to="modules.module",
                verbose_name="Модуль",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course",
                to="modules.course",
                verbose_name="Курс",
            ),
        ),
    ]
